TEST_CONN_USER=sa
TEST_CONN_PASSWORD=Darpa@dev01
TEST_CONN_SERVER_NAME=localhost:1433
CONN_DB_NAME=master
CONN_APP_NAME=ESC_SKv1.0
DB_EDITION=Basic
RANGE_SHARD_MAP_NAME=CustomerIDRangeShardMap
LIST_SHARD_MAP_NAME=CustomerIDListShardMap
RANGE_SHARD_NAME_FORMAT=Elastic_RangeShard%s
LIST_SHARD_NAME_FORMAT=Elastic_ListShard%s
INITIAL_SHARD_SCRIPT=InitializeShard.sql